name: slide_engine_showcase
description: Showcasing my flutter slide engine with go_router.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  go_router: ^5.2.4
  url_launcher: ^6.1.7
  flutter_syntax_view: ^4.0.0
  ionicons: ^0.2.1
  video_player: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
